### ISSUE TITLE
[Feature 2: Profile]

### ISSUE THREAD

**Issue by Teerawat6509650476** [wuttipat6509650716/cs360_group#10]
พัฒนาฟีเจอร์โปรไฟล์ของผู้ใช้ สามารถดู และ แก้ไข 

- [x] Task 1 : #25 
- [x] Task 2 : #26 
- [x] Task 3 : #27 (**ต้องทำ Task1 เสร็จก่อน**)
- [x] Task 4 : #28

**Comment by wuttipat6509650716** [comment]
LGTM!!!!!!!!!!!!!!!!!!
