### ISSUE TITLE
ข้อมูลจาก API Profile มาแสดงผล บนหน้าโปรไฟล์

### ISSUE THREAD

**Issue by Napat6509650492** [wuttipat6509650716/cs360_group#27]
Title: นำเข้าข้อมูลผู้ใช้และแสดงผล
Description: เพิ่มฟังก์ชันการทำงานในการดึงและแสดงข้อมูลผู้ใช้ในหน้าโปรไฟล์
Tasks:

- [x] เชื่อมต่อกับ API ของ backend เพื่อดึงข้อมูลผู้ใช้

- [x] แสดงรายละเอียดของผู้ใช้ (ชื่อ, อีเมล, ฯลฯ) บนหน้า

Acceptance Criteria:

- [x] ข้อมูลผู้ใช้ต้องถูกดึงมาจาก backend อย่างถูกต้อง

- [x] ข้อมูลต้องแสดงอย่างถูกต้องบนหน้าโปรไฟล์

**Comment by Teerawat6509650476** [comment]
LGTM!!!!!!!!!
