### ISSUE TITLE
Profile_Unit_Test

### ISSUE THREAD

**Issue by Napat6509650492** [wuttipat6509650716/cs360_group#44]
### Title
should verify isOwner middleware behavior for various scenarios

### Description
Implement test cases for the isOwner middleware to verify its responses based on different conditions:

- When the user is not authenticated.
- When the ID is missing.
- When the ID is not a digit.
- When the profile does not exist.
- When the user is not the owner.
- When the user is the owner.
- When an internal server error occurs.

### Test Cases:

1. **Test Case for Unauthenticated User:**

      - [x] Set ctx.state.user to null.
      - [x] Expect ctx.unauthorized to be called with "User authentication is required."

2. **Test Case for Missing ID:**
      - [x] Set ctx.params.id to undefined.
      - [x] Expect ctx.badRequest to be called with "Profile ID is required."
      - [x] Test Case for Invalid ID:

3. **Set ctx.params.id to 'abc'.**
      - [x] Expect ctx.badRequest to be called with "ID must be digit only."

4. Test Case for Non-Existent Profile:
      - [x] Mock strapi.entityService.findOne to resolve to null.
      - [x] Expect ctx.notFound to be called with "Profile not found."

5. Test Case for Unauthorized User:
      - [x] Mock strapi.entityService.findOne to resolve with a user ID that is not the owner.
      - [x] Expect ctx.unauthorized to be called with "This action is unauthorized."

6. Test Case for Authorized User:
      - [x] Mock strapi.entityService.findOne to resolve with the correct user ID (owner).
      - [x] Expect next to be called.

7. Test Case for Internal Server Error:
      - [x] Mock strapi.entityService.findOne to reject with an error.
      - [x] Expect strapi.log.error to be called with the error.
      - [x] Expect ctx.internalServerError to be called with "An error occurred."

### Expected Result:
Each test case should validate the expected behavior of the middleware based on the described scenario.

### Acceptance Criteria:
- [x]  Implement all specified test cases for the isOwner middleware.

**Comment by Teerawat6509650476** [comment]
LGTM!!!!!!!!!!!!

**Comment by wuttipat6509650716** [comment]
No issues found
