### ISSUE TITLE
Add key in GitHub Secrets

### ISSUE THREAD

**Issue by Napat6509650492** [wuttipat6509650716/cs360_group#56]
###  AWS Credentials
- [x] AWS_ACCESS_KEY_ID
- [x] AWS_SECRET_ACCESS_KEY
- [x] AWS_SESSION_TOKEN
- [x] AWS_REGION

### DockerHub 
- [x] DOCKER_USERNAME
- [x] DOCKER_TOKEN

**Comment by Teerawat6509650476** [comment]
LGTM!!!!!!!!!!!!!!!!
