### ISSUE TITLE
CD 

### ISSUE THREAD

**Issue by Napat6509650492** [wuttipat6509650716/cs360_group#61]
เขียน GitHub WorkFlow สำหรับ CD pipeline เพื่อ Deploy ไปยัง EC2 

- [x] Check  Docker Image ว่ามีมั้ย SaveToFocus-Front, SaveToFocus-Back
- [x] เขียน Script user-data.sh เพื่อ setup ec2 #62 
- [x] Create EC2 ด้วย awscli & นำ docker-compose.yml ไปรันใน EC2

**ให้ใช้ AWS Credentails ใน GitHub Secrets**
       - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION

**Comment by Teerawat6509650476** [comment]
LGTM!!!!!!!!!!!!!
