### ISSUE TITLE
[Feature 1: Register and Authentication]

### ISSUE THREAD

**Issue by Teerawat6509650476** [wuttipat6509650716/cs360_group#8]
Title: Login & register
Description: พัฒนาฟีเจอร์ Login & Register ในหน้าเว็ป fontend
Tasks:

- [x] สร้างเลเอาต์หน้า login
- [x] สร้างเลเอาต์หน้า Register
- [x] นำเลเอาต์มาพัฒนาหน้าเว็ป
- [x] พัฒนา Logic ฝั่งหน้าบ้านให้เรียกใช้ API จากหลังบ้าน #32 

Acceptance Criteria:

- [x] มีหน้า Login สำหรับเข้าสู่ระบบ
- [x] มีหน้า Register สำหรับสมัครสมาชิก
- [x] สามารถ Login เข้าสู้ระบบได้
- [x] สามารถ Register เพื่อสมัครสมาชิกได้

**Comment by Napat6509650492** [comment]
ไม่มีปัญหาใดๆ LGTM
